import { roboto } from "@/constants/Fonts";
import "./globals.css";
import type { Metadata } from "next";
import * as dayjs from "dayjs";
import "dayjs/locale/vi";

dayjs.locale("vi");

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className + " min-h-screen bg-cultured"}>
        {children}
      </body>
    </html>
  );
}
