name: Deploy AI to Cloud Server

on:
  push:
    paths:
      - ".github/workflows/**"
      - "AI/**"
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./AI
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Temporarily disable command-not-found
        run: |
          echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S rm /usr/lib/cnf-update-db

      - name: Update and install dependencies
        run: |
          echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S apt-get update
          echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S apt-get install -y libjpeg8-dev zlib1g-dev

      - name: Restore command-not-found
        run: |
          echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S ln -s /usr/lib/command-not-found /usr/lib/cnf-update-db

  deploy-AI:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Start flask server
        run: echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S systemctl start myflaskapp.service
