# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
      - name: Build the project
        run: npm run build
    
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: .next/

  # Deployment job
  deploy:
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: nextjs-build
          path: .next/

      - name: Start the application with PM2
        run: pm2 restart nextjs-app
