name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

  # Build frontend
  build-frontend:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Cache node_modules
      - uses: actions/cache@v3
        with:
          path: web/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        working-directory: web
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
        working-directory: web
      - run: npm run build
        working-directory: web

  # Deployment frontend
  deploy-frontend:
    runs-on: self-hosted
    needs: build-frontend
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # - name: Start the application with PM2
      #   run: pm2 restart nextjs-app

  # Build backend
  build-backend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Change to web directory
        run: echo "NODE_PATH=$(pwd)/api" >> $GITHUB_ENV
      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: api
