name: Deploy to Servers

on:
  push:
    paths:
      - ".github/**"
    branches:
      - cicd_ssh

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Set up Node 18.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.x
  #     - name: Set up Ruby 3.0.2
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.0.2
  #     - name: Install dependencies frontend
  #       run: |
  #         cd ./web
  #         npm install
  #         npm run build
  #     - name: Install dependencies backend
  #       run: |
  #         cd ./api
  #         bundle install
  #         touch config/application.yml
  #         echo "${{ secrets.PROD_BACKEND }}" > config/application.yml

  deploy:
    runs-on: ubuntu-latest
    # needs: build
    strategy:
      fail-fast: false
      matrix:
        servers: ["27.66.108.160", "116.103.226.252"]
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Create SSH key
        run: |
          mkdir ~/.ssh/
          touch ~/.ssh/tungaws.pem
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/tungaws.pem
          chmod 400 ~/.ssh/tungaws.pem
      - name: Deploy to server
        run: |
          sshpass -p ${{ secrets.SUDO_PASSWORD }} ssh -o StrictHostKeyChecking=no -i ~/.ssh/tungaws.pem runner@${{ matrix.servers }} '
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            
            export PATH="$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"

            export PATH=$PATH:~/.local/bin

            cd social-media-web && git pull origin main;
            cd api && bundle install;
            cd ../web && npm install && npm run build;
          '
