name: Deploy Web App to Cloud Server

on:
  # Runs on pushes targeting the default branch
  # path web and api
  push:
    paths:
      - "web/**"
      - "api/**"
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

  # Build package
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./web
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build
      # - name: Change to web directory
      #   run: |
      #     echo "NODE_PATH=$(pwd)/api" >> $GITHUB_ENV
      #     cd api
      - name: Change to api directory
        run: cd ../api

      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: api
      - name: Set env
        run: |
          touch application.yml
          echo "${{ secrets.PROD_BACKEND }}" > application.yml
        working-directory: api/config

  # Deployment
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./web
    needs: build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Start the application with PM2
        run: pm2 restart nextjs-app
      - name: Change to api directory
        run: cd ../api
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Start puma server
        run: echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S systemctl start puma.service
