name: Deploy Web App to Cloud Server

on:
  push:
    paths:
      - "web/**"
      - "api/**"
      - ".github/workflows/web.yml"
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set up AWS credentials
        run: |
          sudo apt-get install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-southeast-1
          aws configure set default.output json

      - name: Install dependencies, run tests and upload test coverage result to S3
        run: |
          cd ./web
          npm ci  
          npm run build
          npm run test 
          aws s3 rm s3://intern-viettel-storage-bucket/frontend --recursive
          aws s3 sync ./coverage/lcov-report s3://intern-viettel-storage-bucket/frontend

  # Deployment
  CD:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        servers-backend: ["34.142.196.144"]
        servers-frontend: ["116.103.227.16"]
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/tunggcp
          echo "${{ secrets.SSH_PRIVATE_KEY_BACKEND }}" > ~/.ssh/tunggcp
          chmod 600 ~/.ssh/tunggcp
          touch ~/.ssh/frontend.pem
          echo "${{ secrets.SSH_PRIVATE_KEY_FRONTEND }}" > ~/.ssh/frontend.pem
          chmod 400 ~/.ssh/frontend.pem

      - name: Deploy backend to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/tunggcp tunggcp@${{ matrix.servers-backend }} '
          echo "${{ secrets.PROD_BACKEND }}" > social-media-web/api/config/application.yml
          cd social-media-web && bash backend-script.sh
          '
      - name: Deploy frontend to server
        run: | 
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/frontend.pem root@${{ matrix.servers-frontend }} '
          ls -a
          cd social-media-web && bash frontend-script.sh
          '
        
# sshpass -p ${{ secrets.SUDO_PASSWORD }} 