name: Deploy Web App to Cloud Server

on:
  push:
    paths:
      - "web/**"
      - ".github/workflows/**"
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

  # Build package
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./web
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build

  # Deployment
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Start the application with PM2
        run: |
          npm install pm2 -g
          pm2 restart nextjs-app
    
